name: Create new dns record service
run-name: ${{ inputs.trigger_reference }}
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of service'
        required: true
        type: string
      record_type:
        description: 'Type of DNS record to be created'
        required: true
        default: 'A'
        type: choice
        options:
          - 'A'
          - 'CNAME'
      addresses:
        description: 'List of IP addresses (required if record_type is "A")'
        type: string


jobs:
  set_json_data:
    name: Set JSON data
    runs-on: ubuntu-24.04
    outputs:
      json_data: ${{ steps.set_json_data.outputs.json_data }}
    steps:
      - name: Set JSON data
        id: set_json_data
        run: |
          json_data=$(echo '${{ toJson(github.event.inputs) }}')
          addresses="${{ github.event.inputs.addresses }}"
          json_addresses=$(echo "$addresses" | jq -R 'split(",")')
          updated_json=$(echo "$json_data" | jq --argjson addresses "$json_addresses" '.addresses = $addresses')
          echo "updated_json=${updated_json}"
